FROM python:3.8-slim

ADD . /opt/app
WORKDIR /opt/app
RUN pip install numpy --extra-index-url https://www.piwheels.org/simple \
    && pip install --no-cache-dir -r requirements.txt --extra-index-url https://www.piwheels.org/simple
CMD [ "python", "./main.py" ]